### ISSUE TITLE
Failed to parse a valid string

### ISSUE THREAD

**Issue by simoami** [Leonidas-from-XIV/node-xml2js#305] opened 2016-06-06 20:09 UTC
Hello,
xml2js/sax is failing to parse the following string. can you tell me if you see anything wrong with it? I'm not seeing any illegal characters that need escaping.

```
<status><status_code>500</status_code><message>NUMBER_OF_RETRIES_NEXTSERVER_EXCEEDED :1 retries, while making a call with load balancer: connection timed out: ec2-51-21-211-121.us-west-2.compute.amazonaws.com/51.21.211.121:8080</message></status>
```

error is:
```
Error: Could not parse the response from the remote service. \n ERROR: Invalid character in entity name\nLine: 0\nColumn: 164\nChar: =\n    at parseStringCallback (/project/src/lib/helpers.js:98:13)\n    at Parser.<anonymous> (/project/node_modules/xml2js/lib/xml2js.js:488:18)
```

**Comment by Leonidas-from-XIV** [comment] 2016-06-06 20:11
Can you provide a minimal example?

**Comment by simoami** [comment] 2016-06-06 20:18
Sure, here:

```
var parseString = require('xml2js').parseString;

// parse an xml response
function parseXML(body, cb) {
  parseString(body, function parseStringCallback(err, result) {
    if (err) {
      // unify error message
      err = new Error('Could not parse the response from the remote service. \n ERROR: ' + err.message);
      err.status = 422; // 422 - Unprocessable Entity
      return cb(err);
    }
    cb(null, result);
  });
}

// Run demo function
var message = "<status><status_code>500</status_code><message>NUMBER_OF_RETRIES_NEXTSERVER_EXCEEDED :1 retries, while making a call with load balancer: connection timed out: ec2-51-21-211-121.us-west-2.compute.amazonaws.com/51.21.211.121:8080</message></status>";

parseString(message, function (err, json) {
    console.log(err, json);
});
```

**Comment by Leonidas-from-XIV** [comment] 2016-06-06 20:21
That parses just fine for me:

```
null { status: 
   { status_code: [ '500' ],
     message: [ 'NUMBER_OF_RETRIES_NEXTSERVER_EXCEEDED :1 retries, while making a call with load balancer: connection timed out: ec2-51-21-211-121.us-west-2.compute.amazonaws.com/51.21.211.121:8080' ] } }
```

**Comment by simoami** [comment] 2016-06-06 20:23
strange, I use "xml2js": "^0.4.13"

**Comment by simoami** [comment] 2016-06-06 20:24
let me check again

**Comment by Leonidas-from-XIV** [comment] 2016-06-06 20:27
Maybe check the version of sax. I have 1.2.1 locally and that works alright.

**Comment by simoami** [comment] 2016-06-06 20:28
mine has 1.1.5

**Comment by simoami** [comment] 2016-06-06 20:37
Thanks for testing. I ended up wrapping values in `<![CDATA[ ]]>` and it worked.

**Comment by Leonidas-from-XIV** [comment] 2016-06-06 21:30
That shouldn't be necessary, but as I can't reproduce and you found a solution I'm closing this.

**Closed by Leonidas-from-XIV** 2016-06-06 21:30 UTC
