### ISSUE TITLE
Output xml is not same as input xml without editing

### ISSUE THREAD

**Issue by impromptu100** [Leonidas-from-XIV/node-xml2js#402] opened 2017-09-12 20:42 UTC
I am using xml2js version 0.4.19
```
var fs = require('fs');
var xml2js = require('xml2js');
var parser = new xml2js.Parser({preserveChildrenOrder : true, explicitArray: false});
    parser.parseString(this.fileData, function(err, result){
        if(err) {
          throw new Error('Cannot parse Input XML: ' + err);
        }
        
        var util = require('util');
        console.log(util.inspect(result, false, null));
        
        // create a new builder object and then convert
        // our json back to xml.
        var builder = new xml2js.Builder();
        var xml = builder.buildObject(result);
        //var returnxml = xml.replace(/<\/?[0-9]{1,}>/g,'');
        
        fs.writeFileSync('edited-test.xml', xml);
        console.log('logfile.xml updated');
                  
    });
```

Here is the xml that I am using as input

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="comm" time="1272.711632">
    <testsuite name="SimpleTest" time="34.393977">
      <testsuite name="SimpleTest::function" time="34.393977">
        <testcase name="test1" time="22.838998"/>
        <testcase name="test2" time="11.554979"/>
      </testsuite>
    </testsuite>
    <testsuite name="ModerateTest" time="34.010964">
      <testsuite name="ModerateTest::function" time="34.010964">
        <testcase name="test2" time="17.088365"/>
        <testcase name="test2" time="16.922599"/>
      </testsuite>
    </testsuite>
    <testsuite name="ComplexTest" time="49.054462">
      <testsuite name="ComplexTest::function" time="34.571204">
        <testcase name="test1" time="34.571204"/>
      </testsuite>
      <testsuite name="ComplexTest:function2" time="14.483258">
        <testcase name="test1" time="14.483258"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```
After parsing xml and outputting the xml back to a file, it looks different with nodes with name $

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testsuites>
  <testsuite name="comm" time="1272.711632">
    <testsuite>
      <$>
        <name>SimpleTest</name>
        <time>34.393977</time>
      </$>
      <testsuite name="SimpleTest::function" time="34.393977">
        <testcase name="test1" time="22.838998"/>
        <testcase name="test2" time="11.554979"/>
      </testsuite>
      <$>
        <name>ModerateTest</name>
        <time>34.010964</time>
      </$>
      <testsuite name="ModerateTest::function" time="34.010964">
        <testcase name="test2" time="17.088365"/>
        <testcase name="test2" time="16.922599"/>
      </testsuite>
    </testsuite>
    <testsuite name="ComplexTest" time="49.054462">
      <testsuite name="ComplexTest::function" time="34.571204">
        <testcase name="test1" time="34.571204"/>
      </testsuite>
      <testsuite name="ComplexTest:function2" time="14.483258">
        <testcase name="test1" time="14.483258"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```

Any idea what is going on? Am I passing incorrect parameters or missing anything? I did try without passing explictArray or the preserveChildrenOrder parameters and still does not work.

--
**Update**

I switched to using libxmljs and it did not have this problem.

**Comment by sigmasoldi3r** [comment] 2018-03-07 15:43
Thanks @impromptu100 for providing an alternative, we're dropping this library from production.

**Comment by jcsahnwaldt** [comment] 2018-06-09 12:36
Issue can be closed. I can't reproduce this issue with xml2js 0.4.19 (current npm version). I can't run the original code because `this.fileData` isn't defined, so I guess there was something wrong with the xml in `fileData`, or the given code is not the code that had the issue.

Here's the code I ran:

```
var xml2js = require('xml2js');

xml = `
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="comm" time="1272.711632">
    <testsuite name="SimpleTest" time="34.393977">
      <testsuite name="SimpleTest::function" time="34.393977">
        <testcase name="test1" time="22.838998"/>
        <testcase name="test2" time="11.554979"/>
      </testsuite>
    </testsuite>
    <testsuite name="ModerateTest" time="34.010964">
      <testsuite name="ModerateTest::function" time="34.010964">
        <testcase name="test2" time="17.088365"/>
        <testcase name="test2" time="16.922599"/>
      </testsuite>
    </testsuite>
    <testsuite name="ComplexTest" time="49.054462">
      <testsuite name="ComplexTest::function" time="34.571204">
        <testcase name="test1" time="34.571204"/>
      </testsuite>
      <testsuite name="ComplexTest:function2" time="14.483258">
        <testcase name="test1" time="14.483258"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>`;

console.log(xml);
console.log();

var parser = new xml2js.Parser({preserveChildrenOrder : true, explicitArray: false});
parser.parseString(xml, function(err, result){
    if(err) throw new Error('Cannot parse Input XML: ' + err);
    
    console.dir(result, {depth: null});
    console.log();
    
    // create a new builder object and then convert
    // our json back to xml.
    var builder = new xml2js.Builder();
    var xml = builder.buildObject(result);
    console.log(xml);
});
```

And here's the output:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="comm" time="1272.711632">
    <testsuite name="SimpleTest" time="34.393977">
      <testsuite name="SimpleTest::function" time="34.393977">
        <testcase name="test1" time="22.838998"/>
        <testcase name="test2" time="11.554979"/>
      </testsuite>
    </testsuite>
    <testsuite name="ModerateTest" time="34.010964">
      <testsuite name="ModerateTest::function" time="34.010964">
        <testcase name="test2" time="17.088365"/>
        <testcase name="test2" time="16.922599"/>
      </testsuite>
    </testsuite>
    <testsuite name="ComplexTest" time="49.054462">
      <testsuite name="ComplexTest::function" time="34.571204">
        <testcase name="test1" time="34.571204"/>
      </testsuite>
      <testsuite name="ComplexTest:function2" time="14.483258">
        <testcase name="test1" time="14.483258"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>

{ testsuites: 
   { testsuite: 
      { '$': { name: 'comm', time: '1272.711632' },
        testsuite: 
         [ { '$': { name: 'SimpleTest', time: '34.393977' },
             testsuite: 
              { '$': { name: 'SimpleTest::function', time: '34.393977' },
                testcase: 
                 [ { '$': { name: 'test1', time: '22.838998' } },
                   { '$': { name: 'test2', time: '11.554979' } } ] } },
           { '$': { name: 'ModerateTest', time: '34.010964' },
             testsuite: 
              { '$': { name: 'ModerateTest::function', time: '34.010964' },
                testcase: 
                 [ { '$': { name: 'test2', time: '17.088365' } },
                   { '$': { name: 'test2', time: '16.922599' } } ] } },
           { '$': { name: 'ComplexTest', time: '49.054462' },
             testsuite: 
              [ { '$': { name: 'ComplexTest::function', time: '34.571204' },
                  testcase: { '$': { name: 'test1', time: '34.571204' } } },
                { '$': { name: 'ComplexTest:function2', time: '14.483258' },
                  testcase: { '$': { name: 'test1', time: '14.483258' } } } ] } ] } } }

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testsuites>
  <testsuite name="comm" time="1272.711632">
    <testsuite name="SimpleTest" time="34.393977">
      <testsuite name="SimpleTest::function" time="34.393977">
        <testcase name="test1" time="22.838998"/>
        <testcase name="test2" time="11.554979"/>
      </testsuite>
    </testsuite>
    <testsuite name="ModerateTest" time="34.010964">
      <testsuite name="ModerateTest::function" time="34.010964">
        <testcase name="test2" time="17.088365"/>
        <testcase name="test2" time="16.922599"/>
      </testsuite>
    </testsuite>
    <testsuite name="ComplexTest" time="49.054462">
      <testsuite name="ComplexTest::function" time="34.571204">
        <testcase name="test1" time="34.571204"/>
      </testsuite>
      <testsuite name="ComplexTest:function2" time="14.483258">
        <testcase name="test1" time="14.483258"/>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
```

**Comment by Leonidas-from-XIV** [comment] 2018-06-09 13:27
@jcsahnwaldt Thanks for triaging this! Closing.

**Closed by Leonidas-from-XIV** 2018-06-09 13:27 UTC
