### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by dotob** [Leonidas-from-XIV/node-xml2js#168] opened 2015-01-16 13:20 UTC
λ npm test

> xml2js@0.4.4 test D:\tmp\node-xml2js
> zap

bom/test decoded BOM... passed
builder/test building basic XML structure... passed
builder/test setting XML declaration... passed
builder/test pretty by default... passed
builder/test setting indentation... passed
builder/test headless option... passed
builder/test explicit rootName is always used: 1. when there is only one element... passed
builder/test explicit rootName is always used: 2. when there are multiple elements... passed
builder/test default rootName is used when there is more than one element in the hash... passed
builder/test when there is only one first-level element in the hash, that is used as root... passed
builder/test parser -> builder roundtrip... failed

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
  at TypeError (<anonymous>:null:null)
  at Parser.emit (events.js:74:15)
  at Parser.exports.Parser.Parser.parseString (D:\tmp\node-xml2js\lib\xml2js.js:407:16)
  at Parser.parseString (D:\tmp\node-xml2js\lib\xml2js.js:6:61)
  at Object.exports.parseString (D:\tmp\node-xml2js\lib\xml2js.js:433:19)
  at D:\tmp\node-xml2js\test\builder.test.coffee:123:14
  at fs.js:271:14
  at Object.oncomplete (fs.js:107:15)

**Comment by Leonidas-from-XIV** [comment] 2015-01-16 14:55
That's odd, because the test succeeds on Travis CI as well as on my system.

**Comment by dotob** [comment] 2015-01-16 14:57
i thought it might be windows. but i tried in ubuntu and it didnt succed there either. 

does the test from my pull request succeed on your machine?

```coffeescript
  'test parsing a date': (test) ->
    expected = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><adate>2000-01-01T00:00:00.0</adate>'
    opts = renderOpts: pretty: false
    builder = new xml2js.Builder opts
    obj = {"adate": new Date(2000, 0, 1, 1, 0, 0, 0)}
    actual = builder.buildObject obj
    diffeq expected, actual
    test.finish()
```

**Comment by Leonidas-from-XIV** [comment] 2015-01-16 15:39
No, that test fails (only the one you added):

```
builder/test parsing a date... failed

/home/marek/node-xml2js/test/builder.test.coffee:21
      throw patch;
            ^
Index: test
===================================================================
--- test	expected
+++ test	actual
@@ -1,1 +1,1 @@
+<?xml version="1.0" encoding="UTF-8" standalone="yes"?><adate/>
\ No newline at end of file
-<?xml version="1.0" encoding="UTF-8" standalone="yes"?><adate>2000-01-01T00:00:00.0</adate>
\ No newline at end of file
```

**Comment by dotob** [comment] 2015-01-16 15:47
yes it does. i want to demonstrate an error in der builder. it doesnt write out date nodes. 

i couldnt fix it. 

...

**Comment by Leonidas-from-XIV** [comment] 2015-01-17 15:28
But having a failing test in the regression test suite serves hardly any purpose, except making it more difficult to see whether there errors.

Also, I am not sure what the proper serialization for dates is supposed to be. Is there any agreed-upon notation in XML?

So, I'm closing this for now.

**Closed by Leonidas-from-XIV** 2015-01-17 15:28 UTC

**Comment by dotob** [comment] 2015-01-19 07:39
hi,

i thought a test would make easier to develop a solution as it shows the problem in a reproducible environment. to have a failing test should be the first step.

i think the library should have this feature because it seems not very good to ignore a basic type like datetime. and yes there is a agreed upon format for datetime: http://www.w3.org/TR/xmlschema-2/#dateTime. i think it is represented like this in the test. 

i took a look at the sourcecode but couldnt figure the fix by myself. perhaps later or you could give a hint how its done (or add comments ;-) ).

**Comment by Leonidas-from-XIV** [comment] 2015-01-20 20:57
The probelm with a failing test is, that every time someone pushed something, it would throw an error and for example for new features you wouldn't know if the test was supposed to fail or not.

(That said, the JS->XML route is not a big priority for `xml2js` because generating the exact XML you want is rather complex. Most of the time it is just causing trouble that someone has to fix)
